"""Initial schema

Revision ID: 23c537c4c61a
Revises: 
Create Date: 2026-04-21 10:50:51.958189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c537c4c61a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('freight_bill_id', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carriers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('carrier_code', sa.String(length=20), nullable=False),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='carrierstatus'), nullable=False),
    sa.Column('onboarded_on', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrier_code')
    )
    op.create_table('carrier_contracts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('carrier_id', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', name='contractstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_rate_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.String(length=50), nullable=False),
    sa.Column('lane', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('rate_per_kg', sa.Float(), nullable=True),
    sa.Column('rate_per_unit', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_capacity_kg', sa.Integer(), nullable=True),
    sa.Column('alternate_rate_per_kg', sa.Float(), nullable=True),
    sa.Column('min_charge', sa.Float(), nullable=False),
    sa.Column('fuel_surcharge_percent', sa.Float(), nullable=False),
    sa.Column('revised_on', sa.Date(), nullable=True),
    sa.Column('revised_fuel_surcharge_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['carrier_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('carrier_id', sa.String(length=50), nullable=False),
    sa.Column('contract_id', sa.String(length=50), nullable=False),
    sa.Column('lane', sa.String(length=50), nullable=False),
    sa.Column('shipment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('in_transit', 'partially_delivered', 'delivered', name='shipmentstatus'), nullable=False),
    sa.Column('total_weight_kg', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['carrier_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bills_of_lading',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('actual_weight_kg', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freight_bills',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('carrier_id', sa.String(length=50), nullable=True),
    sa.Column('carrier_name', sa.String(length=200), nullable=False),
    sa.Column('bill_number', sa.String(length=100), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('shipment_reference', sa.String(length=50), nullable=True),
    sa.Column('lane', sa.String(length=50), nullable=False),
    sa.Column('billed_weight_kg', sa.Integer(), nullable=False),
    sa.Column('rate_per_kg', sa.Float(), nullable=True),
    sa.Column('billing_unit', sa.String(length=20), nullable=True),
    sa.Column('base_charge', sa.Float(), nullable=False),
    sa.Column('fuel_surcharge', sa.Float(), nullable=False),
    sa.Column('gst_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('processing_status', sa.Enum('ingested', 'processing', 'awaiting_review', 'completed', 'escalated', name='freightbillprocessingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['shipment_reference'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('freight_bill_id', sa.String(length=50), nullable=False),
    sa.Column('matched_contract_id', sa.String(length=50), nullable=True),
    sa.Column('matched_shipment_id', sa.String(length=50), nullable=True),
    sa.Column('matched_bol_ids', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('decision', sa.Enum('auto_approve', 'flag_for_review', 'dispute', 'escalate', name='agentdecision'), nullable=False),
    sa.Column('validation_results', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freight_bill_id'], ['freight_bills.id'], ),
    sa.ForeignKeyConstraint(['matched_contract_id'], ['carrier_contracts.id'], ),
    sa.ForeignKeyConstraint(['matched_shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('freight_bill_id')
    )
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('freight_bill_id', sa.String(length=50), nullable=False),
    sa.Column('agent_state', sa.JSON(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'reviewed', name='reviewqueuestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freight_bill_id'], ['freight_bills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('freight_bill_id')
    )
    op.create_table('human_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_queue_id', sa.Integer(), nullable=False),
    sa.Column('freight_bill_id', sa.String(length=50), nullable=False),
    sa.Column('reviewer_decision', sa.Enum('approve', 'dispute', 'modify', name='reviewdecision'), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('corrected_amount', sa.Float(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freight_bill_id'], ['freight_bills.id'], ),
    sa.ForeignKeyConstraint(['review_queue_id'], ['review_queue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('human_reviews')
    op.drop_table('review_queue')
    op.drop_table('agent_decisions')
    op.drop_table('freight_bills')
    op.drop_table('bills_of_lading')
    op.drop_table('shipments')
    op.drop_table('contract_rate_cards')
    op.drop_table('carrier_contracts')
    op.drop_table('carriers')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
